version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      DB_URL: ${DB_URL}
      DB_NAME: ${DB_URL}
