version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - blog-app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - blog-app-network

networks:
  blog-app-network:
    driver: bridge

volumes:
  mongodb-data:
